# Generated by Django 3.2 on 2021-04-08 10:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(related_name='ad_comments', through='pages.Comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
